# Generated by Django 5.2.3 on 2025-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookuphistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل استدعاء بيانات', 'verbose_name_plural': 'سجلات استدعاء البيانات'},
        ),
        migrations.AlterField(
            model_name='lookuphistory',
            name='query_type',
            field=models.CharField(max_length=50, verbose_name='نوع المعرّف'),
        ),
        migrations.AlterField(
            model_name='lookuphistory',
            name='query_value',
            field=models.CharField(max_length=100, verbose_name='القيمة المُستخدمة في البحث'),
        ),
        migrations.AlterField(
            model_name='lookuphistory',
            name='result_found',
            field=models.BooleanField(default=False, verbose_name='تم العثور على النتيجة'),
        ),
        migrations.AlterField(
            model_name='lookuphistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البحث'),
        ),
    ]
