# Generated by Django 5.2.3 on 2025-08-15 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_alter_lookuphistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuphistory',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='action',
            field=models.CharField(blank=True, help_text='مثل: استعلام / تحديث', max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة/رسالة النظام'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='meter_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العداد'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الهوية يجب أن يكون 10 أرقام.', code='invalid_nid')], verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', 'رقم الجوال غير صالح (9–15 رقم).', code='invalid_phone')], verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='unit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='كود الوحدة'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookup_histories', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='lookuphistory',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='المتصفح/العميل'),
        ),
        migrations.AlterField(
            model_name='lookuphistory',
            name='query_type',
            field=models.CharField(choices=[('meter', 'رقم العداد'), ('account', 'رقم الحساب'), ('national', 'رقم الهوية'), ('phone', 'رقم الجوال'), ('unit', 'كود الوحدة'), ('unknown', 'غير محدد')], default='unknown', max_length=50, verbose_name='نوع المعرّف'),
        ),
        migrations.AlterField(
            model_name='lookuphistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية'),
        ),
        migrations.AddIndex(
            model_name='lookuphistory',
            index=models.Index(fields=['-timestamp'], name='lookup_look_timesta_99d6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='lookuphistory',
            index=models.Index(fields=['query_type', 'query_value'], name='lookup_look_query_t_6d9f5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lookuphistory',
            constraint=models.CheckConstraint(condition=models.Q(('query_value', ''), _negated=True), name='lookup_query_value_not_empty'),
        ),
    ]
