# Generated by Django 5.2.3 on 2025-08-16 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_lookuphistory_account_number_lookuphistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookuphistory',
            name='query_type',
            field=models.CharField(choices=[('meter', 'رقم العداد'), ('account', 'رقم الحساب'), ('national', 'رقم الهوية'), ('phone', 'رقم الجوال'), ('unit', 'كود الوحدة'), ('email', 'البريد الإلكتروني'), ('name', 'الاسم'), ('unknown', 'غير محدد')], default='unknown', max_length=50, verbose_name='نوع المعرّف'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم')),
                ('meter_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم العداد')),
                ('account_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم الحساب')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الهوية يجب أن يكون 10 أرقام.', code='invalid_nid')], verbose_name='رقم الهوية')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{9,15}$', 'رقم الجوال غير صالح (9–15 رقم).', code='invalid_phone')], verbose_name='رقم الجوال')),
                ('unit_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='كود الوحدة')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['full_name', 'account_no'],
                'indexes': [models.Index(fields=['meter_no'], name='lookup_cust_meter_n_48a812_idx'), models.Index(fields=['account_no'], name='lookup_cust_account_6b3703_idx'), models.Index(fields=['national_id'], name='lookup_cust_nationa_961ebe_idx'), models.Index(fields=['mobile'], name='lookup_cust_mobile_d36d8c_idx'), models.Index(fields=['unit_code'], name='lookup_cust_unit_co_49471c_idx')],
            },
        ),
    ]
