# Generated by Django 5.2.3 on 2025-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل دخول', 'verbose_name_plural': 'سجلات الدخول'},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت التنفيذ'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user_identifier',
            field=models.CharField(max_length=100, verbose_name='معرّف المستخدم'),
        ),
    ]
