# Generated by Django 5.2.3 on 2025-08-13 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_accesslog_options_alter_accesslog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='رقم الجوال')),
                ('national_id', models.CharField(max_length=20, verbose_name='رقم الهوية')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddField(
            model_name='accesslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='يُسجل عند توفره', null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='سلاسل واصف المتصفح عند الحاجة', max_length=255, null=True, verbose_name='متصفح/عميل'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('OTP', 'تحقق OTP'), ('VIEW', 'عرض صفحة'), ('FAIL', 'محاولة فاشلة')], db_index=True, default='VIEW', max_length=20, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التنفيذ'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user_identifier',
            field=models.CharField(db_index=True, help_text='مثال: رقم الجوال أو البريد الإلكتروني', max_length=100, verbose_name='معرّف المستخدم'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user_identifier', 'timestamp'], name='access_acce_user_id_ad17ca_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['action', 'timestamp'], name='access_acce_action_954097_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
