# Generated by Django 5.2.3 on 2025-08-13 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_userprofile_accesslog_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='رقم الجوال')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإرسال')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات')),
            ],
            options={
                'verbose_name': 'رمز تحقق',
                'verbose_name_plural': 'رموز التحقق',
                'indexes': [models.Index(fields=['phone', 'created_at'], name='access_otpr_phone_6eb45d_idx')],
            },
        ),
    ]
