# Generated by Django 5.2.3 on 2025-08-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='الرقم المرجعي'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Pending', max_length=20, verbose_name='الحالة الحالية'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=50, verbose_name='نوع الطلب'),
        ),
    ]
